Bump com.google.guava:guava-testlib from 33.0.0-jre to 33.2.1-jre (#461)
* Bump com.google.guava:guava-testlib from 33.0.0-jre to 33.2.1-jre

Bumps [com.google.guava:guava-testlib](https://github.com/google/guava) from 33.0.0-jre to 33.2.1-jre.
- [Release notes](https://github.com/google/guava/releases)
- [Commits](https://github.com/google/guava/commits)

---
updated-dependencies:
- dependency-name: com.google.guava:guava-testlib
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* Fix weird issue with annotation in test compilation

Without this change `./gradlew :executor:compileTestJava` fails with:

```
> Task :executor:compileTestJava
/home/runner/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/33.2.1-jre/818e780da2c66c63bbb6480fef1f3855eeafa3e4/guava-33.2.1-jre.jar(/com/google/common/collect/Streams.class): warning: Cannot find annotation method 'replacement()' in type 'InlineMe': class file for com.google.errorprone.annotations.InlineMe not found
/home/runner/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/33.2.1-jre/818e780da2c66c63bbb6480fef1f3855eeafa3e4/guava-33.2.1-jre.jar(/com/google/common/collect/Streams.class): warning: Cannot find annotation method 'replacement()' in type 'InlineMe'
/home/runner/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/33.2.1-jre/818e780da2c66c63bbb6480fef1f3855eeafa3e4/guava-33.2.1-jre.jar(/com/google/common/collect/Streams.class): warning: Cannot find annotation method 'value()' in type 'InlineMeValidationDisabled': class file for com.google.errorprone.annotations.InlineMeValidationDisabled not found
/home/runner/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/33.2.1-jre/818e780da2c66c63bbb6480fef1f3855eeafa3e4/guava-33.2.1-jre.jar(/com/google/common/collect/Streams.class): warning: Cannot find annotation method 'replacement()' in type 'InlineMe'
/home/runner/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/33.2.1-jre/818e780da2c66c63bbb6480fef1f3855eeafa3e4/guava-33.2.1-jre.jar(/com/google/common/collect/Streams.class): warning: Cannot find annotation method 'value()' in type 'InlineMeValidationDisabled'
/home/runner/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/33.2.1-jre/818e780da2c66c63bbb6480fef1f3855eeafa3e4/guava-33.2.1-jre.jar(/com/google/common/collect/Streams.class): warning: Cannot find annotation method 'replacement()' in type 'InlineMe'
/home/runner/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/33.2.1-jre/818e780da2c66c63bbb6480fef1f3855eeafa3e4/guava-33.2.1-jre.jar(/com/google/common/collect/Streams.class): warning: Cannot find annotation method 'value()' in type 'InlineMeValidationDisabled'
/home/runner/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/33.2.1-jre/818e780da2c66c63bbb6480fef1f3855eeafa3e4/guava-33.2.1-jre.jar(/com/google/common/collect/Streams.class): warning: Cannot find annotation method 'replacement()' in type 'InlineMe'
/home/runner/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/33.2.1-jre/818e780da2c66c63bbb6480fef1f3855eeafa3e4/guava-33.2.1-jre.jar(/com/google/common/collect/Streams.class): warning: Cannot find annotation method 'value()' in type 'InlineMeValidationDisabled'
error: warnings found and -Werror specified
```

`./gradlew allDeps` should the correct annotations dependency being part of the test compilation classpath.

Go figure.

* Switch to adding module

see: https://github.com/google/error-prone/releases/tag/v2.26.1

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Big Andy <8012398+big-andy-coates@users.noreply.github.com>